apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: fluentpos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: iammukeshm/fluentpos-catalog-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          
