apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: fluentpos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: iammukeshm/fluentpos-gateway:latest
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "k8s"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - port: 5000
    targetPort: 80
          
