version: '3.8'
name: fluentpos
services:
  catalogservice:
    container_name: "catalog-service"
    image: iammukeshm/fluentpos-catalog-service
    ports:
      - "5001:5001"
      - "6001:6001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:6001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
