version: '3.8'
name: fluentpos
services:
  gateway:
    container_name: "gateway"
    image: iammukeshm/fluentpos-gateway
    pull_policy: always
    ports:
      - 5010:5010
      - 5100:5100
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fluentpos 

  catalog:
    container_name: "catalog"
    image: iammukeshm/fluentpos-catalog-service
    pull_policy: always
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      catalog-pg:
        condition: service_healthy
    networks:
     - fluentpos    
  catalog-pg:
    container_name: "catalog-postgres"
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DATABASE=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5200:5432
    volumes:
      - catalog-pg-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - fluentpos   
volumes:
  catalog-pg-data:
    
networks:
  fluentpos:
    name:  fluentpos
