name: build-push-docker
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch: 
jobs:     
  docker:
    name: Build Container Images & Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Build Gateway Image
        working-directory: ./src/api-gateway
        run: docker build -t ${{ github.actor }}/fluentpos-gateway:$(date +%Y%m%d) -t ${{ github.actor }}/fluentpos-gateway:latest .
      - name: Push Gateway Image
        run: docker push ${{ github.actor }}/fluentpos-gateway --all-tags
      - name: Build Catalog Service Image
        working-directory: ./src/
        run: docker build -t ${{ github.actor }}/fluentpos-catalog-service:$(date +%Y%m%d) -t ${{ github.actor }}/fluentpos-catalog-service:latest -f services/catalog/Dockerfile .
      - name: Push Catalog Service Image
        run: docker push ${{ github.actor }}/fluentpos-catalog-service --all-tags     
