name: Push Docker Image To Hub

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push Catalog Service Image to Docker Hub
      working-directory: ./deployments/docker-compose/
      run: docker compose push catalogservice:$(date +%s)
